### NEWS API Query Param Search
GET http://localhost:3000/player_news_headlines?first_name=Joe&last_name=Haden


### Twitter Keyword based filtered tweet search
GET http://localhost:3000/player_twitter_keywords?first_name=Tom&last_name=Brady
